- name: restart vmware services
  shell: 'sudo /Applications/VMware\ Fusion.app/Contents/Library/services/services.sh --stop; sleep 3; sudo /Applications/VMware\ Fusion.app/Contents/Library/services/services.sh --start'
  ignore_errors: yes

- name: restart nfsd
  shell: 'sudo nfsd restart'
